"""Deterministic semantic model used by tests and local demonstrations."""

from __future__ import annotations

from collections import deque

from paperops.comparison.models import (
    ComparisonCell,
    ComparisonCellStatus,
    ComparisonExtraction,
    ComparisonExtractionRequest,
)
from paperops.research.models import (
    AnswerSynthesisRequest,
    EvidenceAssessment,
    EvidenceAssessmentRequest,
    ModelCallUsage,
    QueryRewrite,
    QueryRewriteRequest,
    ResearchAnswer,
)


class FakeResearchModel:
    """Return scripted typed decisions without network or model dependencies."""

    name = "fake-research-model"

    def __init__(
        self,
        *,
        assessments: list[EvidenceAssessment | Exception] | None = None,
        rewrites: list[QueryRewrite | Exception] | None = None,
        answers: list[ResearchAnswer | Exception] | None = None,
        comparison_extractions: list[ComparisonExtraction | Exception] | None = None,
        default_min_evidence: int = 1,
    ) -> None:
        """Configure optional outcomes and retain every typed request."""
        self._assessments = deque(assessments or [])
        self._rewrites = deque(rewrites or [])
        self._answers = deque(answers or [])
        self._comparison_extractions = deque(comparison_extractions or [])
        self.default_min_evidence = default_min_evidence
        self.assessment_calls: list[EvidenceAssessmentRequest] = []
        self.rewrite_calls: list[QueryRewriteRequest] = []
        self.answer_calls: list[AnswerSynthesisRequest] = []
        self.comparison_calls: list[ComparisonExtractionRequest] = []
        self._usage: list[ModelCallUsage] = []

    def _record_usage(self, operation: str, *, success: bool) -> None:
        self._usage.append(
            ModelCallUsage(operation=operation, success=success, latency_ms=0.0)
        )

    def drain_usage(self) -> list[ModelCallUsage]:
        """Return call-count telemetry without claiming provider token usage."""
        usage, self._usage = self._usage, []
        return usage

    async def assess_evidence(
        self,
        request: EvidenceAssessmentRequest,
    ) -> EvidenceAssessment:
        """Return a scripted judgment or a deterministic hit-count decision."""
        self.assessment_calls.append(request)
        if self._assessments:
            outcome = self._assessments.popleft()
            if isinstance(outcome, Exception):
                self._record_usage("assess_evidence", success=False)
                raise outcome
            self._record_usage("assess_evidence", success=True)
            return outcome
        sufficient = len(request.evidence) >= self.default_min_evidence
        result = EvidenceAssessment(
            sufficient=sufficient,
            confidence=1.0,
            rationale="Deterministic fake evidence-count policy.",
            missing_aspects=[] if sufficient else ["additional supporting evidence"],
            relevant_citation_ids=(
                [request.evidence[0].citation_id] if sufficient else []
            ),
        )
        self._record_usage("assess_evidence", success=True)
        return result

    async def rewrite_query(self, request: QueryRewriteRequest) -> QueryRewrite:
        """Return a scripted rewrite or append the first missing aspect."""
        self.rewrite_calls.append(request)
        if self._rewrites:
            outcome = self._rewrites.popleft()
            if isinstance(outcome, Exception):
                self._record_usage("rewrite_query", success=False)
                raise outcome
            self._record_usage("rewrite_query", success=True)
            return outcome
        aspect = request.missing_aspects[0]
        result = QueryRewrite(
            query=f"{request.question} {aspect}",
            reason="Deterministic fake rewrite targeting the recorded gap.",
        )
        self._record_usage("rewrite_query", success=True)
        return result

    async def synthesize_answer(
        self,
        request: AnswerSynthesisRequest,
    ) -> ResearchAnswer:
        """Return a scripted answer or cite the first evidence chunk."""
        self.answer_calls.append(request)
        if self._answers:
            outcome = self._answers.popleft()
            if isinstance(outcome, Exception):
                self._record_usage("synthesize_answer", success=False)
                raise outcome
            self._record_usage("synthesize_answer", success=True)
            return outcome
        first = request.evidence[0]
        result = ResearchAnswer(
            text=f"The available evidence supports the answer [{first.citation_id}].",
            citation_ids=[first.citation_id],
            limitations=["Generated by the deterministic fake research model."],
        )
        self._record_usage("synthesize_answer", success=True)
        return result

    async def extract_comparison(
        self,
        request: ComparisonExtractionRequest,
    ) -> ComparisonExtraction:
        """Return scripted cells or ground every dimension in the first chunk."""
        self.comparison_calls.append(request)
        if self._comparison_extractions:
            outcome = self._comparison_extractions.popleft()
            if isinstance(outcome, Exception):
                self._record_usage("extract_comparison", success=False)
                raise outcome
            self._record_usage("extract_comparison", success=True)
            return outcome
        first = request.evidence[0]
        result = ComparisonExtraction(
            document_id=request.document.document_id,
            cells=[
                ComparisonCell(
                    document_id=request.document.document_id,
                    dimension_id=dimension.dimension_id,
                    status=ComparisonCellStatus.SUPPORTED,
                    claim=(
                        f"{dimension.description} is supported by the indexed "
                        f"document [{first.citation_id}]."
                    ),
                    citation_ids=[first.citation_id],
                    confidence=1.0,
                )
                for dimension in request.dimensions
            ],
        )
        self._record_usage("extract_comparison", success=True)
        return result
