"""Deterministic semantic model used by tests and local demonstrations."""

from __future__ import annotations

from collections import deque

from paperops.research.models import (
    AnswerSynthesisRequest,
    EvidenceAssessment,
    EvidenceAssessmentRequest,
    QueryRewrite,
    QueryRewriteRequest,
    ResearchAnswer,
)


class FakeResearchModel:
    """Return scripted typed decisions without network or model dependencies."""

    name = "fake-research-model"

    def __init__(
        self,
        *,
        assessments: list[EvidenceAssessment | Exception] | None = None,
        rewrites: list[QueryRewrite | Exception] | None = None,
        answers: list[ResearchAnswer | Exception] | None = None,
        default_min_evidence: int = 1,
    ) -> None:
        """Configure optional outcomes and retain every typed request."""
        self._assessments = deque(assessments or [])
        self._rewrites = deque(rewrites or [])
        self._answers = deque(answers or [])
        self.default_min_evidence = default_min_evidence
        self.assessment_calls: list[EvidenceAssessmentRequest] = []
        self.rewrite_calls: list[QueryRewriteRequest] = []
        self.answer_calls: list[AnswerSynthesisRequest] = []

    async def assess_evidence(
        self,
        request: EvidenceAssessmentRequest,
    ) -> EvidenceAssessment:
        """Return a scripted judgment or a deterministic hit-count decision."""
        self.assessment_calls.append(request)
        if self._assessments:
            outcome = self._assessments.popleft()
            if isinstance(outcome, Exception):
                raise outcome
            return outcome
        sufficient = len(request.evidence) >= self.default_min_evidence
        return EvidenceAssessment(
            sufficient=sufficient,
            confidence=1.0,
            rationale="Deterministic fake evidence-count policy.",
            missing_aspects=[] if sufficient else ["additional supporting evidence"],
        )

    async def rewrite_query(self, request: QueryRewriteRequest) -> QueryRewrite:
        """Return a scripted rewrite or append the first missing aspect."""
        self.rewrite_calls.append(request)
        if self._rewrites:
            outcome = self._rewrites.popleft()
            if isinstance(outcome, Exception):
                raise outcome
            return outcome
        aspect = request.missing_aspects[0]
        return QueryRewrite(
            query=f"{request.question} {aspect}",
            reason="Deterministic fake rewrite targeting the recorded gap.",
        )

    async def synthesize_answer(
        self,
        request: AnswerSynthesisRequest,
    ) -> ResearchAnswer:
        """Return a scripted answer or cite the first evidence chunk."""
        self.answer_calls.append(request)
        if self._answers:
            outcome = self._answers.popleft()
            if isinstance(outcome, Exception):
                raise outcome
            return outcome
        first = request.evidence[0]
        return ResearchAnswer(
            text=f"The available evidence supports the answer [{first.citation_id}].",
            citation_ids=[first.citation_id],
            limitations=["Generated by the deterministic fake research model."],
        )
